### ISSUE TITLE
ModuleNotFoundError: No module named 'command'

### ISSUE THREAD

**Issue by 0xabdi** [brthor/docker-save-last-layer#4]
I am running `Python 3.10.9` on an M1 Mac and running into the below error.

```console
$ d-save-last -o . 3474b0c62e52
Traceback (most recent call last):
  File "/opt/homebrew/bin/d-save-last", line 3, in <module>
    from docker_save_last import main
  File "/opt/homebrew/lib/python3.9/site-packages/docker_save_last/main.py", line 22, in <module>
    from command import Command
ModuleNotFoundError: No module named 'command'
```

Looking at [this](https://docs.python.org/2/library/commands.html), it shows `command` has been deprecated in favor of `subprocess`

**Comment by brthor** [comment]
This repo is not actively maintained for many years and was developed with python 2.

`Command` is a wrapper of subprocess here:
https://github.com/brthor/docker-save-last-layer/blob/master/docker_save_last/command.py

I suggest using python 2 or updating the repo to support python 3.
